version: "3"
services:
  db:
    image:  ${REPO_PREFIX}/db:${BUILD_BUILDNUMBER}
    ports:
      - 27017:27017
      - 28017:28017
    links: 
      - db:mongo 
    networks:
      - pu
  order:
    image:  ${REPO_PREFIX}/order:${BUILD_BUILDNUMBER}
    ports:
      - 8080:8080
    depends_on: 
      - db
    networks:
      - pu
  web:
    image:  ${REPO_PREFIX}/web:${BUILD_BUILDNUMBER}
    ports:
      - 80:8080
    depends_on: 
      - db
    networks:
      - pu
networks:
  pu: 
  
